### PR TITLE
Add Create/Delete additional shiftstack clusters

### PR DESCRIPTION
**Pull request by akrzos**
This is what I am using to deploy a hub cluster with working public api and ingress DNS and then following up with being able to deploy multiple spoke clusters on OSP.  So far numbers reached are 1 hub cluster with 55 spoke clusters.

### CODE REVIEW

**Comment by masco** [comment]
Can one of the admins verify this patch?

**Comment by venkataanil** [comment]
@akrzos @masco can you please fix shift_stack_vars.yaml vars. I am fine with other changes as this patch can help others if they want to try multiple OCP clusters with jetpack.

**Comment by akrzos** [comment]
> @akrzos @masco can you please fix shift_stack_vars.yaml vars. I am fine with other changes as this patch can help others if they want to try multiple OCP clusters with jetpack.

I believe I fixed to the desired defaults, I will move this out of draft now, I also re-based it to avoid and conflicts.  Thanks!

**Comment by asyedham** [comment]
run tests

**Comment by akrzos** [comment]
@asyedham hold on just a second before merge I have some ansible tasks to give the masters nvme mounted storage now

**Comment by akrzos** [comment]
Ok this is ready for merge I added a toggle var `ocp_master_etcd_nvme` to use the nvme for the master nodes.  One would use this for the hub cluster to improve the perf/scale of the hub cluster:

Example:
```
Etcd on nvme:
PASS: Throughput is 150 writes/s
PASS: Slowest request took 0.071727s
PASS: Stddev is 0.002728s
PASS

Etcd on regular osp disk:
PASS: Throughput is 150 writes/s
Slowest request took too long: 0.676013s
PASS: Stddev is 0.022386s
FAIL
```

**Comment by psuriset** [comment]
Looks good to me. Merging now.

**Pull request merged**
