### PR TITLE
Add log directory

### PR DESCRIPTION
**Pull request by asyedham**

### CODE REVIEW

**Comment by asyedham** [comment]
@smalleni Could please have look

**Comment by smalleni** [comment]
Please see my comment on https://github.com/redhat-performance/jetpack/pull/71

Currently your redirect will not get stderr.

For that you need
command > file 2>&1 

^ means you are redirecting stderr also to stdout.

**Comment by asyedham** [comment]
@smalleni I have done suggested changes. could you please have look

**Comment by asyedham** [comment]
closing this. Will raise new PR

**Pull request closed without merging**
